import Head from 'next/head'
import Header from '@/components/layout/Header'
import Home from "./home"
import Input from '@/components/form/Input'

export default function Index() {
  return (
    <div className="">
      <Head>
        <title>React Food Ordering</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="true" />
        
      </Head>
      <Header />
      <Home />
      <div className='p-20 container mx-auto'>
        <Input type="email" placeholder="E-mail" isrequired={true} />
      </div>
    </div>
  )
}
