import Head from 'next/head'
import Home from "./home"
import axios from 'axios'

export default function Index({categoryList, productList}) {
  return (
    <div className="">
      <Head>
        <title>React Food Ordering</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        
      </Head>
      <Home categoryList = { categoryList } productList = { productList } />
    </div>
  )
}



export const getServerSideProps = async () => {
  const categories = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/categories`)
  const products = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/products`)
  
  return {
    props: {
      categoryList: categories.data ? categories.data : [],
      productList: products.data ? products.data : [],
    }
  }
}
